spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service?serverTimezone=UTC
    username: root
    password: 091094
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true
  kafka:
    bootstrap-servers: ${hostname.local}:${kafka.port}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${hostname.local}
  client:
    service-url:
      defaultZone: ${hostname.local}:${eureka.port}/eureka
    fetch-registry: true
    register-with-eureka: true
